rpc:
  "rpc1":
    url: "https://api.mainnet-beta.solana.com"
    rpc_type: "solanarpc"
  "jito-rpc1":
    url: "https://ny.mainnet.block-engine.jito.wtf/api/v1/transactions"
    rpc_type: "jito"
  "bloxroute-rpc1":
    url: "https://ny.solana.dex.blxrbdn.com/api/v2/submit"
    rpc_type: "bloxroute"
    auth: ""
  "nextblock-rpc1":
    url: "https://fra.nextblock.io/api/v2/submit"
    rpc_type: "nextblock"
    auth: ""

geyser_url: ""
geyser_x_token: ""

http_rpc: "https://api.mainnet-beta.solana.com"
ws_rpc: "wss://api.mainnet-beta.solana.com"

private_key: ""

compute_unit_price: 10000000
compute_unit_limit: 100000

tip: 0.001
buy_amount: 0.0001
min_amount_out: 100